### ISSUE TITLE
define with promise does not wait until promise is fulfilled

### ISSUE THREAD

**Issue by pke** [jokeyrhyme/requirejs-promise#7]
Given this scenario:

models/Inspection.js

```
define(["models", "promise!models/Defect"], function(models, defect) {
});
```

app.js

```
define(["models", "models/Inspection"], function(models, inspection) {
  // here inspection === undefined
});
```

in app.js I end up with inspection being undefined.
The same code works, if I use require("models/inspection") later inside my app module though.

So does promise not work with define?

**Comment by jokeyrhyme** [comment]
Hmm. It definitely should. I'll look at this over the weekend and see what's going on here.

**Comment by jokeyrhyme** [comment]
I added a new test case to cover `define()`:
https://github.com/jokeyrhyme/requirejs-promise/blob/master/examples/combination-amd.js
https://github.com/jokeyrhyme/requirejs-promise/blob/master/test/tests.js#L189-L215
I haven't modified the plugin at all, and the tests are passing. It's a bit puzzling.

I often get `undefined` when I have accidentally introduced a circular dependency in Require.JS. Is it possible that this is what is happening here?

**Comment by pke** [comment]
yes, a circular dependency is possible. I need to step through my code. First time usage of requirejs in a big project. So still a bit unclear when to use require/define.

**Comment by jokeyrhyme** [comment]
The function you pass to `require()` is immediately executed, once the dependencies have been met.

The function you pass to `define()` is put away for later, and only executed if something else depends on it.

So all Require.JS projects end up with at least one `require()` call (or the `data-main` attribute), otherwise nothing happens. :)

**Comment by pke** [comment]
Yes, thanks.
I think I have a clue why it might not have been working, but I don't have the old code anymore.
I wrote `define('models', function() {})` which is very different from the correct `define(['models'], function() {})`
But it shows also that the requirejs API for define is not very good, if you can make such easy mistakes like forgetting the array braces.

**Comment by jokeyrhyme** [comment]
Anonymous modules are defined like this: `define(['a', 'b'], function (a, b) {});`

Named modules are defined like this: `define('id', ['a', 'b'], function (a, b) {});`

Usually, you will leave all your modules anonymous, and let the Require.JS optimisation process automatically fix up the IDs and the references at the end. This also allows consumers of your modules to define their own names for them, instead of you hard-coding a name that might (unknowingly) clash downstream.

No worries. You made me add another test, which is never a bad thing. :)
